version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.local
    environment:
      - WATCHPACK_POLLING=true
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
