# version: '3.8'
# services:
#   myblog:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '3000:3000'
#     volumes:
#       - ./src:/app/src:ro
#     env_file:
#       - ./.env.local
#     environment:
#       - WATCHPACK_POLLING=true

version: '3'
services:
  nextjs:
    build: ./
  nginx:
    build: ./nginx
    ports:
      - 80:80
